services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=life-os

  minio:
    image: minio/minio
    container_name: life-os-minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=cris
      - MINIO_ROOT_PASSWORD=crisfdevpwd
    networks:
      mynet:
        aliases:
          - my-localhost

    volumes:
      - minio_data:/data
    ports:
      - "9002:9000"
      - "9003:9001"

networks:
  mynet:
    driver: bridge

volumes:
  minio_data:
    driver: local
